// This file was automatically generated by lister-gen

package v1alpha1

// StackListerExpansion allows custom methods to be added to
// StackLister.
type StackListerExpansion interface{}

// StackNamespaceListerExpansion allows custom methods to be added to
// StackNamespaceLister.
type StackNamespaceListerExpansion interface{}
